# Generated by Django 3.1.2 on 2020-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('vender', models.CharField(blank=True, max_length=50, null=True)),
                ('adapter', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('cycle', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('chip1', models.CharField(blank=True, max_length=100, null=True)),
                ('chip1_protocols', models.CharField(blank=True, max_length=50, null=True)),
                ('chip2', models.CharField(blank=True, max_length=100, null=True)),
                ('chip2_protocols', models.CharField(blank=True, max_length=50, null=True)),
                ('network_technology_standard', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_id', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_pw', models.CharField(blank=True, max_length=50, null=True)),
                ('ssid_2_4', models.CharField(db_column='ssid_2.4', max_length=50)),
                ('ssid_2_4_password', models.CharField(db_column='ssid_2.4_password', max_length=50)),
                ('ssid_2_4_bssid', models.CharField(blank=True, db_column='ssid_2.4_bssid', max_length=50, null=True)),
                ('ssid_2_4_band', models.CharField(blank=True, db_column='ssid_2.4_band', max_length=50, null=True)),
                ('ssid_5', models.CharField(blank=True, max_length=50, null=True)),
                ('ssid_5_password', models.CharField(blank=True, max_length=50, null=True)),
                ('ssid_5_bssid', models.CharField(blank=True, max_length=50, null=True)),
                ('ssid_5_band', models.CharField(blank=True, max_length=50, null=True)),
                ('fw', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApBorrowHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rent_time', models.DateTimeField()),
                ('back_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ap_borrow_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bios', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('join_tiom', models.DateTimeField()),
                ('alive_time', models.DurationField(blank=True, null=True)),
                ('dashboard_uuid', models.UUIDField()),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('release_time', models.TimeField()),
                ('path', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('package_name', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('mail', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deliverable_name', models.TextField()),
                ('short_name', models.CharField(max_length=50)),
                ('vender_id', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('subsys_device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('subsys_vender_id', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'module',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('update_time', models.DateTimeField()),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('behavior', models.CharField(blank=True, max_length=100, null=True)),
                ('codename', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('target', models.CharField(blank=True, max_length=50, null=True)),
                ('development_center', models.CharField(blank=True, max_length=200, null=True)),
                ('cycle', models.CharField(blank=True, max_length=50, null=True)),
                ('forecast_cycle', models.CharField(blank=True, max_length=50, null=True)),
                ('series', models.CharField(blank=True, max_length=200, null=True)),
                ('forecast_series', models.CharField(blank=True, max_length=200, null=True)),
                ('chipset', models.CharField(blank=True, max_length=200, null=True)),
                ('marketing_name', models.CharField(blank=True, max_length=200, null=True)),
                ('odm', models.CharField(blank=True, db_column='ODM', max_length=50, null=True)),
                ('sepm', models.CharField(blank=True, db_column='SEPM', max_length=50, null=True)),
                ('pdm', models.CharField(blank=True, db_column='PDM', max_length=50, null=True)),
            ],
            options={
                'db_table': 'platform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('wwan', models.TextField()),
                ('wlan', models.TextField()),
                ('bt', models.TextField()),
                ('lan', models.TextField()),
                ('rfid', models.TextField()),
                ('nfc', models.TextField()),
                ('path', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField()),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'script',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('period', models.DurationField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('task_uuid', models.UUIDField()),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tool',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uut',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(max_length=50)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('phase', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('scrap_reason', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('scrap', models.BooleanField()),
                ('keyin_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UutBorrowHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rent_time', models.DateTimeField()),
                ('back_time', models.TimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uut_borrow_history',
                'managed': False,
            },
        ),
    ]
