# Generated by Django 3.1.2 on 2020-10-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UutPhase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phase_text', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'uut_phase',
                'managed': False,
            },
        ),
    ]
